[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./Simple FPS.x86_64 --headless"
restartPolicyType = "always"

[[deploy.environmentVariables]]
name = "PORT"
value = "8080"