[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/local/bin/godot --headless --main-pack server.pck"
restartPolicyType = "always"

[[deploy.environmentVariables]]
name = "PORT"
value = "7000"