[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./simple-fps-server --headless"
restartPolicyType = "always"

[[deploy.environmentVariables]]
name = "PORT"
value = "8080"