[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/local/bin/godot --headless --path /app res://scenes/ServerMain.tscn"
restartPolicyType = "always"

[[deploy.environmentVariables]]
name = "PORT"
value = "7000"